# new file!

## headline? 

I should probably make it look better with a title
Edit 3: made it a title

Okay, actually retrieved the file correctly this time.

LONG line: wikipedia on Github: Projects on GitHub.com can be accessed and managed using the standard Git command-line interface; all standard Git commands work with it. GitHub.com also allows users to browse public repositories on the site. Multiple desktop clients and Git plugins are also available. The site provides social networking-like functions such as feeds, followers, wikis (using wiki software called Gollum) and a social network graph to display how developers work on their versions ("forks") of a repository and what fork (and branch within that fork) is newest. Anyone can browse and download public repositories but only registered users can contribute content to repositories. With a registered user account, users are able to have discussions, manage repositories, submit contributions to others' repositories, and review changes to code. GitHub.com began offering limited private repositories at no cost in January 2019 (limited to three contributors per project). Previously, only public repositories were free.[63][64][65] On April 14, 2020, GitHub made "all of the core GitHub features" free for everyone, including "private repositories with unlimited collaborators."[66] The fundamental software that underpins GitHub is Git itself, written by Linus Torvalds, creator of Linux. The additional software that provides the GitHub user interface was written using Ruby on Rails and Erlang by GitHub, Inc. developers Wanstrath,[67] Hyett, and Preston-Werner.

short line: Github is confusing.


TESTING ANOTHER PUSH TO HOMEWORK/PRACTICE REPO